import { afterEach,beforeEach,describe,expect,it } from "vitest";
import fs from "node:fs"; import path from "node:path";
import { closeDb,db } from "../lib/db"; import { ingest,setApplicationStatus,setReviewStatus,workflowQueues } from "../lib/jobs"; import { generateMaterials,materialArtifacts } from "../lib/materials"; import { resolveOfficial } from "../lib/discovery";
const file="/private/tmp/v06-workflow.sqlite",store="/private/tmp/v06-workflow-store";
beforeEach(()=>{closeDb();process.env.JOB_AGENT_DB_PATH=file;process.env.JOB_AGENT_STORAGE_ROOT=store;fs.rmSync(file,{force:true});fs.rmSync(store,{recursive:true,force:true});});afterEach(()=>{closeDb();fs.rmSync(file,{force:true});fs.rmSync(store,{recursive:true,force:true});});
const add=()=>ingest({company:"Acme",title:"Engineer",url:"https://careers.example/jobs/1",sourceName:"Careers",description:"TypeScript engineering"}).job;
describe("V0.6 workflow queues",()=>{it("moves a job through review, tailor, ready to apply, and active work",()=>{const j=add();expect(workflowQueues().review.map(x=>x.job_id)).toEqual([j.job_id]);setReviewStatus(j.job_id,"INTERESTED");expect(workflowQueues().tailor.map(x=>x.job_id)).toEqual([j.job_id]);db().prepare("UPDATE jobs SET material_status='READY' WHERE id=?").run(j.id);expect(workflowQueues().materialsReady.map(x=>x.job_id)).toEqual([j.job_id]);setApplicationStatus(j.job_id,"READY_TO_APPLY");expect(workflowQueues().readyToApply.map(x=>x.job_id)).toEqual([j.job_id]);setApplicationStatus(j.job_id,"APPLIED");const q=workflowQueues();expect(q.readyToApply).toEqual([]);expect(q.active.map(x=>x.job_id)).toEqual([j.job_id]);});it("keeps skipped and closed jobs out of earlier actionable queues",()=>{const j=add();setReviewStatus(j.job_id,"SKIPPED");const q=workflowQueues();expect(q.review).toEqual([]);expect(q.historical.map(x=>x.job_id)).toEqual([j.job_id]);});});
describe("V0.6 material access",()=>{it("lists only existing generated files without changing job states",async()=>{fs.mkdirSync(path.join(store,"profile"),{recursive:true});fs.writeFileSync(path.join(store,"profile","profile.yaml"),"name: Test Candidate\nskills: [TypeScript]\nsummary: Factual test summary.\n");const j=add();setReviewStatus(j.job_id,"INTERESTED");expect(materialArtifacts(j)).toEqual([]);await generateMaterials(j.job_id);const before=db().prepare("SELECT review_status,material_status,application_status FROM jobs WHERE id=?").get(j.id);const artifacts=materialArtifacts(db().prepare("SELECT * FROM jobs WHERE id=?").get(j.id));expect(artifacts.map(x=>x.key)).toEqual(["resumePdf","resumeDocx","letterPdf","letterDocx","packagePdf"]);fs.rmSync(artifacts[0].file);expect(materialArtifacts(db().prepare("SELECT * FROM jobs WHERE id=?").get(j.id)).map(x=>x.key)).not.toContain("resumePdf");expect(db().prepare("SELECT review_status,material_status,application_status FROM jobs WHERE id=?").get(j.id)).toEqual(before);});});
describe("V0.6 direct-careers JD preservation",()=>{it("retains richer factual text from the already reached direct page",async()=>{const previous=globalThis.fetch;globalThis.fetch=async()=>new Response("<main><h1>Engineer</h1><p>Build TypeScript services for German customers.</p><p>Collaborate with product and operations teams.</p></main>");try{const job=await resolveOfficial({company:"Acme",title:"Engineer",url:"https://careers.acme.example/jobs/1",sourceName:"Web search",description:"Engineer",discoveredVia:"web search"});expect(job.sourceName).toBe("Official careers page");expect(job.description).toContain("Build TypeScript services for German customers.");}finally{globalThis.fetch=previous;}});});
