import { afterEach,describe,expect,it } from "vitest";
import { BundesagenturAdapter } from "../lib/discovery";
const preferences={roleFamilies:["Softwareentwickler"],location:"Germany"};
const record={stellenangebotsTitel:"Softwareentwickler (m/w/d)",firma:"Deutsche Rentenversicherung Bund (DRV Bund)",stellenlokationen:[{adresse:{ort:"Würzburg",plz:"97084",land:"DEUTSCHLAND"}}],referenznummer:"14225-9b2ce6645fccdfb3-S",datumErsteVeroeffentlichung:"2026-09-16",externeURL:"https://example.invalid/job"};
afterEach(()=>{delete process.env.BA_API_KEY;});
describe("Bundesagentur v6 compatibility",()=>{
  it("maps v6 search, normalizes Germany, sends the key, and uses a bounded detail request",async()=>{const original=globalThis.fetch,requested:string[]=[];process.env.BA_API_KEY="jobboerse-jobsuche";globalThis.fetch=async(input:any,init:any)=>{const url=String(input);requested.push(url);expect(init.headers).toEqual({"X-API-Key":"jobboerse-jobsuche"});return url.includes("/v6/jobs")?new Response(JSON.stringify({ergebnisliste:[record]})):new Response(JSON.stringify({stellenangebotsBeschreibung:"Build reliable software services, collaborate with product teams, and document technical decisions for customers."}));};try{const [job]=await new BundesagenturAdapter(preferences,25).discover();expect(requested[0]).toContain("/pc/v6/jobs");expect(new URL(requested[0]).searchParams.get("wo")).toBe("Deutschland");expect(requested[1]).toContain(`/pc/v4/jobdetails/${Buffer.from(record.referenznummer).toString("base64")}`);expect(job).toMatchObject({company:record.firma,title:record.stellenangebotsTitel,location:"Würzburg",externalId:`ba:${record.referenznummer}`,contentStatus:"SUBSTANTIVE"});}finally{globalThis.fetch=original;}});
  it("queries each role separately and aggregates unique IDs before bounded details",async()=>{const original=globalThis.fetch,requested:string[]=[];const rows=[record,{...record,referenznummer:"second",stellenangebotsTitel:"Product Developer",firma:"Second GmbH"},{...record,referenznummer:"third",stellenangebotsTitel:"IoT Developer",firma:"Third GmbH"}];globalThis.fetch=async(input:any)=>{const url=String(input);if(url.includes("/v6/jobs")){const role=new URL(url).searchParams.get("was")||"";requested.push(role);return new Response(JSON.stringify({ergebnisliste:role==="First"?[rows[0],rows[1]]:[rows[0],rows[2]]}));}return new Response(JSON.stringify({}));};try{const jobs=await new BundesagenturAdapter({roleFamilies:["First","Second"]},3).discover();expect(requested).toEqual(["First","Second"]);expect(jobs.map(j=>j.externalId)).toEqual([`ba:${record.referenznummer}`,"ba:second","ba:third"]);}finally{globalThis.fetch=original;}});
  it("preserves provider errors for search HTTP failures",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response("forbidden",{status:403});try{await expect(new BundesagenturAdapter(preferences,25).discover()).rejects.toThrow("BA returned 403");}finally{globalThis.fetch=original;}});
});
