import { afterEach, beforeEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { buildEvaluationInput, persistJobAnalysis, readJobAnalysis } from "../lib/agent-workflow";
import { dashboardWorkflow } from "../lib/dashboard";
import { closeDb, db } from "../lib/db";
import { runDiscovery } from "../lib/discovery";
import { ingest, setReviewStatus } from "../lib/jobs";
import { generateMaterials, materialArtifacts } from "../lib/materials";

const file = "/private/tmp/v074-agent-workflow.sqlite", store = "/private/tmp/v074-agent-workflow-store";
const profile = "name: Test Candidate\nskills: [TypeScript, SQL]\nlanguages: [German, English]\nsummary: Factual profile summary.\nexperience:\n  - employer: Acme\n    title: Engineer\n    bullets: [Built TypeScript services.]\n";
const jd = "Senior Engineer in Berlin. Hybrid work. German and English required. The role includes a six month probation period and bAV.";
const add = (description = jd, contentStatus?: "SUBSTANTIVE" | "INSUFFICIENT") => ingest({ company: "Acme", title: "Senior Engineer", location: "Berlin", workModel: "Hybrid", url: `https://careers.example/${Math.random()}`, sourceName: "Careers", description, contentStatus }).job;
const analysis = (jobId: string) => ({ schemaVersion: "v0.7", jobId, role: { archetype: "Engineering", seniority: { text: "Senior", evidence: "Senior Engineer" }, workModel: { text: "Hybrid", evidence: "Hybrid work" }, location: { text: "Berlin", evidence: "Berlin" } }, requirements: [{ text: "German and English", evidence: "German and English required" }, { text: "TypeScript services", evidence: "Senior Engineer" }], matches: [{ requirement: "TypeScript services", candidateFactRefs: [{ kind: "skill", index: 0 }, { kind: "experienceBullet", index: 0, bulletIndex: 0 }] }], gaps: [], germanyDachConsiderations: [{ topic: "language", evidence: "German and English required" }, { topic: "workModel", evidence: "Hybrid work" }, { topic: "probationOrNotice", evidence: "probation period" }, { topic: "bav", evidence: "bAV" }], strengths: [{ kind: "skill", index: 0 }], keywords: [{ text: "TypeScript", priority: 1, evidence: "Senior Engineer" }], tailoringPlan: { skillIndexes: [0], experiences: [{ index: 0, bulletIndexes: [0] }], keywords: ["TypeScript"] }, evaluation: { score: 4.5 }, provenance: { candidateSource: "profile/profile.yaml", approvedFactRefs: [{ kind: "skill", index: 0 }, { kind: "experience", index: 0 }, { kind: "experienceBullet", index: 0, bulletIndex: 0 }] }, unsupportedClaims: [] });

beforeEach(() => { closeDb(); process.env.JOB_AGENT_DB_PATH = file; process.env.JOB_AGENT_STORAGE_ROOT = store; fs.rmSync(file, { force: true }); fs.rmSync(store, { recursive: true, force: true }); fs.mkdirSync(path.join(store, "profile"), { recursive: true }); fs.writeFileSync(path.join(store, "profile", "profile.yaml"), profile); });
afterEach(() => { closeDb(); fs.rmSync(file, { force: true }); fs.rmSync(store, { recursive: true, force: true }); });

describe("v0.7.4 Codex job-agent workflow", () => {
  it("keeps the repository skill and Career Ops policy read-only", () => { const skill = fs.readFileSync(path.join(process.cwd(), ".agents/skills/job-agent/SKILL.md"), "utf8"); expect(skill).toContain("SQLite"); expect(skill).toContain("Never use Career Ops trackers"); const job = add(); const input = buildEvaluationInput(job.job_id); expect(input.job.jd).toBe(jd); expect(Object.keys(input.policy)).toEqual(["_shared.md", "oferta.md", "_writing.md", "de/_shared.md", "de/angebot.md"]); for (const forbidden of ["data/applications.md", "data/pipeline.md", "data/scan-history.tsv", "data/applications.db", "reports"]) expect(fs.existsSync(path.join(process.cwd(), forbidden))).toBe(false); });
  it("validates, persists, reads, audits, and preserves the legacy score", () => { const job = add(); db().prepare("UPDATE jobs SET score=73 WHERE id=?").run(job.id); const saved = persistJobAnalysis(job.job_id, analysis(job.job_id)); expect(saved.evaluation.score).toBe(4.5); expect(readJobAnalysis(job.job_id)).toMatchObject({ jobId: job.job_id, evaluation: { score: 4.5 } }); expect(db().prepare("SELECT score,analysis_json,status FROM jobs WHERE id=?").get(job.id)).toMatchObject({ score: 73, status: "ANALYZED" }); expect(db().prepare("SELECT action FROM audit_events WHERE job_id=? ORDER BY id DESC LIMIT 1").get(job.id)).toEqual({ action: "AGENT_ANALYSIS_PERSISTED" }); });
  it("invalidates derived materials, returns the job to Tailor, and retains its files", () => { const job = add(); setReviewStatus(job.job_id, "INTERESTED"); db().prepare("UPDATE jobs SET material_status='READY', application_status='READY_TO_APPLY', priority=7, notes='keep', canonical_source='Official' WHERE id=?").run(job.id); const artifact = path.join(store, job.folder_path, "resume", "resume.pdf"); fs.mkdirSync(path.dirname(artifact), { recursive: true }); fs.writeFileSync(artifact, "historical artifact"); persistJobAnalysis(job.job_id, analysis(job.job_id)); const saved = db().prepare("SELECT * FROM jobs WHERE id=?").get(job.id) as any; expect(saved).toMatchObject({ status: "ANALYZED", material_status: "NOT_GENERATED", application_status: "NOT_APPLIED", review_status: "INTERESTED", priority: 7, notes: "keep", canonical_source: "Official" }); expect(materialArtifacts(saved).map(({ key }) => key)).toContain("resumePdf"); expect(dashboardWorkflow([saved]).tailor).toEqual([saved]); expect(dashboardWorkflow([saved]).apply).toEqual([]); expect(db().prepare("SELECT action,detail FROM audit_events WHERE job_id=? AND action='MATERIALS_INVALIDATED_BY_ANALYSIS'").get(job.id)).toEqual({ action: "MATERIALS_INVALIDATED_BY_ANALYSIS", detail: JSON.stringify({ materialStatus: "READY", applicationReset: true }) }); });
  it("invalidates every derived material state while preserving real application history", () => { for (const materialStatus of ["READY", "ERROR", "GENERATING"]) for (const applicationStatus of ["APPLIED", "INTERVIEW", "OFFER", "REJECTED", "WITHDRAWN"]) { const job = add(); db().prepare("UPDATE jobs SET material_status=?, application_status=? WHERE id=?").run(materialStatus, applicationStatus, job.id); persistJobAnalysis(job.job_id, analysis(job.job_id)); expect(db().prepare("SELECT material_status,application_status FROM jobs WHERE id=?").get(job.id)).toEqual({ material_status: "NOT_GENERATED", application_status: applicationStatus }); } });
  it("keeps first-time analysis state unchanged and rejects invalid analysis without partial SQLite writes", () => { const job = add(), before = db().prepare("SELECT analysis_json,status,material_status,application_status FROM jobs WHERE id=?").get(job.id), audits = db().prepare("SELECT count(*) AS n FROM audit_events WHERE job_id=?").get(job.id); persistJobAnalysis(job.job_id, analysis(job.job_id)); expect(db().prepare("SELECT material_status,application_status FROM jobs WHERE id=?").get(job.id)).toEqual({ material_status: "NOT_GENERATED", application_status: "NOT_APPLIED" }); const invalid = add(); db().prepare("UPDATE jobs SET material_status='READY', application_status='READY_TO_APPLY' WHERE id=?").run(invalid.id); const invalidBefore = db().prepare("SELECT analysis_json,status,material_status,application_status FROM jobs WHERE id=?").get(invalid.id), invalidAudits = db().prepare("SELECT count(*) AS n FROM audit_events WHERE job_id=?").get(invalid.id); expect(() => persistJobAnalysis(invalid.job_id, { jobId: invalid.job_id })).toThrow("schemaVersion"); expect(db().prepare("SELECT analysis_json,status,material_status,application_status FROM jobs WHERE id=?").get(invalid.id)).toEqual(invalidBefore); expect(db().prepare("SELECT count(*) AS n FROM audit_events WHERE job_id=?").get(invalid.id)).toEqual(invalidAudits); expect(before).toMatchObject({ analysis_json: null, material_status: "NOT_GENERATED", application_status: "NOT_APPLIED" }); expect(audits).toEqual({ n: 1 }); });
  it("requires JD evidence for Germany/DACH guidance and factual tailoring references", () => { const job = add(), invalid = analysis(job.job_id); invalid.germanyDachConsiderations[0].evidence = "Christmas bonus"; expect(() => persistJobAnalysis(job.job_id, invalid)).toThrow("not evidenced"); persistJobAnalysis(job.job_id, analysis(job.job_id)); expect(readJobAnalysis(job.job_id)?.tailoringPlan).toEqual({ skillIndexes: [0], experiences: [{ index: 0, bulletIndexes: [0] }], keywords: ["TypeScript"] }); });
  it("keeps insufficient source content reviewable but blocks analysis and materials", async () => { const job = add("Senior Engineer", "INSUFFICIENT"); expect(() => buildEvaluationInput(job.job_id)).toThrow("INSUFFICIENT_SOURCE_CONTENT"); expect(() => persistJobAnalysis(job.job_id, analysis(job.job_id))).toThrow("INSUFFICIENT_SOURCE_CONTENT"); await expect(generateMaterials(job.job_id)).rejects.toThrow("INSUFFICIENT_SOURCE_CONTENT"); });
  it("requires explicit evaluation before materials and preserves human workflow decisions", async () => { const job = add(); setReviewStatus(job.job_id, "INTERESTED"); await expect(generateMaterials(job.job_id)).rejects.toThrow("EVALUATION_REQUIRED"); expect(db().prepare("SELECT material_status,application_status FROM jobs WHERE id=?").get(job.id)).toEqual({ material_status: "NOT_GENERATED", application_status: "NOT_APPLIED" }); persistJobAnalysis(job.job_id, analysis(job.job_id)); expect(db().prepare("SELECT material_status,application_status,score FROM jobs WHERE id=?").get(job.id)).toEqual({ material_status: "NOT_GENERATED", application_status: "NOT_APPLIED", score: null }); });
  it("stops discovery at ingest and review without legacy deterministic scoring", async () => { const original = globalThis.fetch, cwd = process.cwd(), directory = fs.mkdtempSync("/private/tmp/v074-discovery-"); try { fs.mkdirSync(path.join(directory, "config")); fs.writeFileSync(path.join(directory, "config/preferences.yaml"), "discovery:\n  roleFamilies: [Engineer]\n"); fs.writeFileSync(path.join(directory, "config/search.yaml"), "providers:\n  - type: greenhouse\n    board: acme\n    enabled: true\n"); process.chdir(directory); globalThis.fetch = async () => new Response(JSON.stringify({ jobs: [{ id: 1, title: "Engineer", absolute_url: "https://boards.greenhouse.io/acme/jobs/1", content: "TypeScript Engineer" }] })); await runDiscovery("config/search.yaml"); expect(db().prepare("SELECT score,analysis_json,status,material_status FROM jobs").get()).toEqual({ score: null, analysis_json: null, status: "DISCOVERED", material_status: "NOT_GENERATED" }); } finally { globalThis.fetch = original; process.chdir(cwd); fs.rmSync(directory, { recursive: true, force: true }); } });
});
