import fs from "node:fs";
import { URL } from "node:url";
import YAML from "yaml";
import { ingest } from "./jobs";
import { db } from "./db";
import type { CandidateProfile, DiscoveredJob, DiscoveryPreferences } from "./types";
import { loadProfile, generateMaterials } from "./materials";
import { loadScoringConfig, scoreJob, type ScoringConfig } from "./scoring";

export interface DiscoveryAdapter { name:string; discover():Promise<DiscoveredJob[]>; }
type WebConfig={enabled?:boolean;maxQueries?:number;maxRawCandidates?:number;maxProcessedCandidates?:number;endpoint?:string};
const jobText=(html:string="")=>html.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
const positive=(value:unknown,fallback:number)=>Number.isInteger(value)&&Number(value)>0?Number(value):fallback;
const hostname=(value:string)=>{try{return new URL(value).hostname.replace(/^www\./,"");}catch{return "";}};
const atsFor=(url:string)=>/greenhouse\.io/.test(url)?"Greenhouse":/lever\.co/.test(url)?"Lever":undefined;
const tenantFor=(url:string,ats?:string)=>{try{const u=new URL(url);return ats==="Greenhouse"?u.pathname.split("/").filter(Boolean)[0]:ats==="Lever"?u.pathname.split("/").filter(Boolean)[0]:undefined;}catch{return undefined;}};
const sourceIdentity=(url:string,ats?:string)=>`${ats||"careers"}:${tenantFor(url,ats)||hostname(url)}`.toLowerCase();
const languageAliases={deutsch:["deutsch","german"],englisch:["englisch","english"],spanisch:["spanisch","spanish"]} as const;
const languageKey=(value:string)=>Object.entries(languageAliases).find(([,aliases])=>aliases.includes(value.toLowerCase() as never))?.[0]||value.toLowerCase();
const germanyEligible=(job:DiscoveredJob,all:string)=>{const context=`${all} ${job.location||""}`;if(!/germany|deutschland/i.test(context)&&!/(european union|\\beu\\b|europe|worldwide|work from anywhere|anywhere in the world)/i.test(context)){const location=(job.location||"").toLowerCase();if(/united states|\\bu\\.?s\\.?\\b|\\busa\\b/.test(location)||/authorized to work in (the )?(united states|u\\.?s\\.?|usa)|us-only|u\\.?s\\.?-based/i.test(all))return false;}return true;};
export const matchesPreferences=(job:DiscoveredJob,p:DiscoveryPreferences)=>{const all=`${job.title} ${job.description}`.toLowerCase();if(p.roleFamilies?.length&&!p.roleFamilies.some(x=>all.includes(x.toLowerCase())))return false;if(p.location?.toLowerCase()==="germany"&&!germanyEligible(job,all))return false;if(p.remotePreference&&p.remotePreference!=="any"&&!`${job.workModel||""} ${job.title} ${job.description}`.toLowerCase().includes(p.remotePreference.toLowerCase()))return false;const mentioned=Object.entries(languageAliases).filter(([,aliases])=>aliases.some(alias=>new RegExp(`\\b${alias}\\b`).test(all))).map(([language])=>language);if(mentioned.length&&p.language?.length&&!mentioned.some(language=>p.language?.map(languageKey).includes(language)))return false;return !(p.postingAgeDays&&job.postedAt&&Date.parse(job.postedAt)<Date.now()-p.postingAgeDays*86400000);};
export class GreenhouseAdapter implements DiscoveryAdapter{name="Greenhouse";constructor(private board:string,private limit?:number){}async discover(){const res=await fetch(`https://boards-api.greenhouse.io/v1/boards/${this.board}/jobs?content=true`);if(!res.ok)throw new Error(`Greenhouse returned ${res.status}`);const b=await res.json() as any;return b.jobs.slice(0,this.limit).map((j:any)=>({company:this.board,title:j.title,location:j.location?.name,url:j.absolute_url,sourceName:"Greenhouse",ats:"Greenhouse",externalId:`greenhouse:${this.board}:${j.id}`,description:jobText(j.content),postedAt:j.updated_at,discoveredVia:"configured ATS"}));}}
export class LeverAdapter implements DiscoveryAdapter{name="Lever";constructor(private company:string,private limit?:number){}async discover(){const res=await fetch(`https://api.lever.co/v0/postings/${this.company}?mode=json`);if(!res.ok)throw new Error(`Lever returned ${res.status}`);const rows=await res.json() as any[];return rows.slice(0,this.limit).map(j=>({company:this.company,title:j.text,location:j.categories?.location,url:j.hostedUrl,sourceName:"Lever",ats:"Lever",externalId:`lever:${this.company}:${j.id}`,description:[j.descriptionPlain,j.additionalPlain].filter(Boolean).join("\n"),workModel:j.workplaceType,discoveredVia:"configured ATS"}));}}
export class BundesagenturAdapter implements DiscoveryAdapter{name="Bundesagentur für Arbeit";constructor(private p:DiscoveryPreferences,private limit:number){}async discover(){const roles=this.p.roleFamilies?.join(" ");if(!roles)return[];const u=new URL("https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v4/jobs");u.searchParams.set("was",roles);u.searchParams.set("wo",this.p.location||"Deutschland");u.searchParams.set("umkreis",String(this.p.radiusKm||0));u.searchParams.set("size",String(this.limit));const res=await fetch(u,{headers:process.env.BA_API_KEY?{"X-API-Key":process.env.BA_API_KEY}:{}});if(!res.ok)throw new Error(`BA returned ${res.status}; set BA_API_KEY if required`);const b=await res.json() as any;return(b.stellenangebote||[]).slice(0,this.limit).map((j:any)=>({company:j.arbeitgeber||"Unknown employer",title:j.beruf||j.titel||"Unknown role",location:j.arbeitsort?.ort||j.arbeitsort?.plz,url:j.refnr?`https://www.arbeitsagentur.de/jobsuche/suche?angebotsart=1&was=${encodeURIComponent(j.refnr)}`:j.url,sourceName:"Bundesagentur für Arbeit",ats:"BA",externalId:j.refnr?`ba:${j.refnr}`:undefined,description:j.beruf||"Job listing from Bundesagentur für Arbeit",postedAt:j.aktuelleVeroeffentlichungsdatum,discoveredVia:"Bundesagentur für Arbeit"}));}}
export class WebSearchAdapter implements DiscoveryAdapter{name="Web search";constructor(private p:DiscoveryPreferences,private c:WebConfig){}async discover(){const out:DiscoveredJob[]=[];for(const role of(this.p.roleFamilies||[]).slice(0,positive(this.c.maxQueries,3))){const u=new URL(this.c.endpoint||"https://www.bing.com/search");u.searchParams.set("q",`${role} ${this.p.location||"Deutschland"} (site:careers.* OR site:jobs.* OR site:greenhouse.io OR site:lever.co)`);const res=await fetch(u,{headers:{"User-Agent":"job-search-agent/0.3 (local personal use)"}});if(!res.ok)throw new Error(`Web search returned ${res.status}`);const html=await res.text();for(const m of html.matchAll(/<li[^>]+class=["'][^"']*\bb_algo\b[^"']*["'][^>]*>[\s\S]*?<h2[^>]*>\s*<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){if(out.length>=positive(this.c.maxRawCandidates,30))break;const url=jobText(m[1]),title=jobText(m[2]);if(/^https?:\/\//.test(url))out.push({company:hostname(url)||"Unknown employer",title:title||"Job listing",url,sourceName:"Web search",ats:atsFor(url),description:title,discoveredVia:"web search"});}}return out.slice(0,positive(this.c.maxProcessedCandidates,15));}}
export async function resolveOfficial(job:DiscoveredJob){if(job.ats)return job;if(/\/careers?\//i.test(new URL(job.url).pathname))return{...job,sourceName:"Official careers page"};try{const res=await fetch(job.url,{headers:{"User-Agent":"job-search-agent/0.3 (local personal use)"}});if(!res.ok)return job;const html=await res.text(),found=[...html.matchAll(/href=["']([^"']+)["']/gi)].map(m=>m[1]).find(x=>/greenhouse\.io|lever\.co|\/careers?\//i.test(x));if(!found)return job;const url=new URL(found,job.url).href,ats=atsFor(url);return{...job,url,sourceName:ats||"Official careers page",ats,externalId:ats&&tenantFor(url,ats)?`${ats.toLowerCase()}:${tenantFor(url,ats)}:${url}`:job.externalId,description:jobText(html).slice(0,20000)||job.description};}catch{return job;}}
export function loadDiscoveryPreferences(path="config/preferences.yaml"):DiscoveryPreferences{const source=fs.existsSync(path)?path:"config/preferences.example.yaml",c=YAML.parse(fs.readFileSync(source,"utf8"))||{},p=c.discovery||c;return{roleFamilies:p.roleFamilies||c.candidate?.roleFamilies||[],location:p.location||c.candidate?.location,radiusKm:p.radiusKm,remotePreference:p.remotePreference||c.candidate?.remotePreference,seniority:p.seniority,language:p.language||c.candidate?.languages,postingAgeDays:p.postingAgeDays,limits:p.limits};}
export function recordSource(job:DiscoveredJob){const ats=job.ats||atsFor(job.url);db().prepare("INSERT INTO source_registry(identity,company,domain,careers_url,ats,tenant,status,last_verified_at,discovered_via) VALUES(?,?,?,?,?, ?,'ACTIVE',CURRENT_TIMESTAMP,?) ON CONFLICT(identity) DO UPDATE SET company=excluded.company,domain=excluded.domain,careers_url=coalesce(excluded.careers_url,source_registry.careers_url),ats=coalesce(excluded.ats,source_registry.ats),tenant=coalesce(excluded.tenant,source_registry.tenant),status='ACTIVE',last_verified_at=CURRENT_TIMESTAMP,discovered_via=excluded.discovered_via").run(sourceIdentity(job.url,ats),job.company,hostname(job.url),ats?job.url:null,ats||null,tenantFor(job.url,ats)||null,job.discoveredVia||job.sourceName);}
export async function scoreForReview(job:any,profile:CandidateProfile,config:ScoringConfig){const r=scoreJob(job.jd_original,profile,config.hardFilters);db().prepare("UPDATE jobs SET score=?,score_explanation=?,status='ANALYZED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(r.score,JSON.stringify(r),job.id);db().prepare("INSERT INTO audit_events(job_id,action,detail) VALUES(?,?,?)").run(job.id,"SCORED",JSON.stringify({score:r.score,autoGenerateDisabled:true}));return r;}
// Legacy API remains available; the discovery workflow now uses scoreForReview.
export async function scoreAndMaybeGenerate(job:any,profile:CandidateProfile,config:ScoringConfig){const r=await scoreForReview(job,profile,config);if(r.score<config.thresholds.autoGenerate)return{score:r.score,generated:false};try{await generateMaterials(job.job_id);return{score:r.score,generated:true};}catch(error:any){db().prepare("UPDATE jobs SET material_status='ERROR' WHERE id=?").run(job.id);return{score:r.score,generated:false,error:error.message};}}
export async function runDiscovery(configPath="config/search.yaml"){const d=db(),run=d.prepare("INSERT INTO discovery_runs(sources_attempted) VALUES(?)").run(""),p=loadDiscoveryPreferences(),c=fs.existsSync(configPath)?YAML.parse(fs.readFileSync(configPath,"utf8"))||{}:{},adapters:DiscoveryAdapter[]=[];for(const x of c.providers||[]){if(!x.enabled)continue;if(x.type==="greenhouse")adapters.push(new GreenhouseAdapter(x.board,x.limit));if(x.type==="lever")adapters.push(new LeverAdapter(x.company,x.limit));}const max=positive(p.limits?.perRun,25);if(c.bundesagentur?.enabled)adapters.push(new BundesagenturAdapter(p,Math.min(max,positive(c.bundesagentur.limit,max))));if(c.webSearch?.enabled)adapters.push(new WebSearchAdapter(p,c.webSearch));const stat={seen:0,newJobs:0,duplicates:0,failures:0,blocked:0,scored:0,generated:0,errors:[] as string[]},profile=loadProfile(),score=profile?loadScoringConfig():undefined;let remaining=max;for(const a of adapters){if(!remaining)break;try{for(const candidate of await a.discover()){if(!remaining)break;if(!matchesPreferences(candidate,p))continue;remaining--;const row=await resolveOfficial(candidate);stat.seen++;recordSource(row);const r=ingest(row);r.created?stat.newJobs++:stat.duplicates++;if(r.created&&profile&&score){await scoreForReview(r.job,profile,score);stat.scored++;}}}catch(error:any){stat.failures++;stat.errors.push(`${a.name}: ${error.message}`);}}d.prepare("UPDATE discovery_runs SET ended_at=CURRENT_TIMESTAMP,sources_attempted=?,jobs_seen=?,new_jobs=?,duplicates=?,failures=?,blocked_sources=?,errors=? WHERE id=?").run(adapters.map(a=>a.name).join(", "),stat.seen,stat.newJobs,stat.duplicates,stat.failures,stat.blocked,stat.errors.join("\n"),run.lastInsertRowid);return{...stat,configured:adapters.length};}
