import fs from "node:fs";
import YAML from "yaml";
import { ingest } from "./jobs";
import { db } from "./db";
import type { DiscoveredJob, CandidateProfile } from "./types";
import { loadProfile, generateMaterials } from "./materials";
import { loadScoringConfig, scoreJob, type ScoringConfig } from "./scoring";
export interface DiscoveryAdapter { name:string; discover():Promise<DiscoveredJob[]>; }
const jobText=(html:string="")=>html.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
export class GreenhouseAdapter implements DiscoveryAdapter { name="Greenhouse"; constructor(private board:string,private limit?:number){} async discover(){const res=await fetch(`https://boards-api.greenhouse.io/v1/boards/${this.board}/jobs?content=true`);if(!res.ok)throw new Error(`Greenhouse returned ${res.status}`);const b=await res.json() as any;return b.jobs.slice(0,this.limit).map((j:any)=>({company:this.board,title:j.title,location:j.location?.name,url:j.absolute_url,sourceName:"Greenhouse",ats:"Greenhouse",externalId:`greenhouse:${this.board}:${j.id}`,description:jobText(j.content),postedAt:j.updated_at}));}}
export class LeverAdapter implements DiscoveryAdapter { name="Lever"; constructor(private company:string,private limit?:number){} async discover(){const res=await fetch(`https://api.lever.co/v0/postings/${this.company}?mode=json`);if(!res.ok)throw new Error(`Lever returned ${res.status}`);const rows=await res.json() as any[];return rows.slice(0,this.limit).map(j=>({company:this.company,title:j.text,location:j.categories?.location,url:j.hostedUrl,sourceName:"Lever",ats:"Lever",externalId:`lever:${this.company}:${j.id}`,description:[j.descriptionPlain,j.additionalPlain].filter(Boolean).join("\n"),workModel:j.workplaceType}));}}
export async function scoreAndMaybeGenerate(job:any,profile:CandidateProfile,config:ScoringConfig){const result=scoreJob(job.jd_original,profile,config.hardFilters);db().prepare("UPDATE jobs SET score=?,score_explanation=?,status='ANALYZED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(result.score,JSON.stringify(result),job.id);db().prepare("INSERT INTO audit_events(job_id,action,detail) VALUES(?,?,?)").run(job.id,"SCORED",JSON.stringify({score:result.score,autoGenerateThreshold:config.thresholds.autoGenerate}));if(result.score<config.thresholds.autoGenerate)return {score:result.score,generated:false};try{await generateMaterials(job.job_id);return {score:result.score,generated:true};}catch(error:any){db().prepare("UPDATE jobs SET material_status='ERROR' WHERE id=?").run(job.id);db().prepare("INSERT INTO audit_events(job_id,action,detail) VALUES(?,?,?)").run(job.id,"MATERIAL_GENERATION_ERROR",error.message);return {score:result.score,generated:false,error:error.message};}}
export async function runDiscovery(configPath="config/search.yaml"){const d=db(),run=d.prepare("INSERT INTO discovery_runs(sources_attempted) VALUES(?)").run(""),adapters:DiscoveryAdapter[]=[];if(fs.existsSync(configPath)){const c=YAML.parse(fs.readFileSync(configPath,"utf8"));for(const p of c.providers||[]){if(!p.enabled)continue;if(p.type==="greenhouse")adapters.push(new GreenhouseAdapter(p.board,p.limit));if(p.type==="lever")adapters.push(new LeverAdapter(p.company,p.limit));}}const stat={seen:0,newJobs:0,duplicates:0,failures:0,blocked:0,scored:0,generated:0,errors:[] as string[]},profile=loadProfile(),config=profile?loadScoringConfig():undefined;for(const a of adapters){try{for(const row of await a.discover()){stat.seen++;const r=ingest(row);r.created?stat.newJobs++:stat.duplicates++;if(r.created&&profile&&config){const result=await scoreAndMaybeGenerate(r.job,profile,config);stat.scored++;if(result.generated)stat.generated++;}}}catch(e:any){stat.failures++;stat.errors.push(`${a.name}: ${e.message}`);}}d.prepare("UPDATE discovery_runs SET ended_at=CURRENT_TIMESTAMP,sources_attempted=?,jobs_seen=?,new_jobs=?,duplicates=?,failures=?,blocked_sources=?,errors=? WHERE id=?").run(adapters.map(a=>a.name).join(", "),stat.seen,stat.newJobs,stat.duplicates,stat.failures,stat.blocked,stat.errors.join("\n"),run.lastInsertRowid);return {...stat,configured:adapters.length};}
