import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { db } from "./db";
import { rankProfileRelevance } from "./relevance";
import { scoreJob } from "./scoring";

type Profile = { name: string; email?: string; phone?: string; location?: string; summary?: string; skills?: string[]; experience?: { employer: string; title: string; dates?: string; bullets?: string[] }[]; education?: string[]; roleFamilies?: string[]; preferredLocations?: string[]; languages?: string[] };
const root = () => process.env.JOB_AGENT_STORAGE_ROOT || process.cwd();
const profilePath = () => path.join(root(), "profile", "profile.yaml");
export function loadProfile(): Profile | undefined { if (!fs.existsSync(profilePath())) return undefined; const p=YAML.parse(fs.readFileSync(profilePath(), "utf8")); return p?.name ? p as Profile : undefined; }
const paras = (lines:string[]) => lines.map(line => new Paragraph({ children:[new TextRun(line)] }));
async function writeDocx(file:string,title:string,lines:string[]) { const doc=new Document({sections:[{children:[new Paragraph({text:title,heading:HeadingLevel.TITLE}),...paras(lines)]}]}); fs.writeFileSync(file,await Packer.toBuffer(doc)); }
async function writePdf(file:string,title:string,lines:string[]) { const pdf=await PDFDocument.create(); const font=await pdf.embedFont(StandardFonts.Helvetica); const bold=await pdf.embedFont(StandardFonts.HelveticaBold); let page=pdf.addPage([612,792]), y=750; const draw=(text:string,size=10,isBold=false)=>{ if(y<55){page=pdf.addPage([612,792]);y=750;} const f=isBold?bold:font; const words=text.split(/\s+/); let row=""; for(const word of words){const next=row?`${row} ${word}`:word;if(f.widthOfTextAtSize(next,size)>510){page.drawText(row,{x:52,y,size,font:f,color:rgb(0,0,0)});y-=size+5;row=word}else row=next;}if(row){page.drawText(row,{x:52,y,size,font:f,color:rgb(0,0,0)});y-=size+5;}}; draw(title,18,true); y-=12; for(const l of lines) draw(l,l.endsWith(":")?12:10,l.endsWith(":")); fs.writeFileSync(file,await pdf.save()); }
function resumeLines(p:Profile,j:any){const relevant=rankProfileRelevance(p,j.jd_original);return [p.name,[p.email,p.phone,p.location].filter(Boolean).join(" | "),"",p.summary||"", "", "Skills:",...relevant.skills.map(s=>`• ${s}`),"", "Experience:",...relevant.experience.flatMap(e=>[`${e.title} — ${e.employer}${e.dates?` (${e.dates})`:""}`,...(e.bullets||[]).map(b=>`• ${b}`)]),"", "Education:",...(p.education||[])];}
function letterLines(p:Profile,j:any){const relevant=rankProfileRelevance(p,j.jd_original);return [p.name,[p.email,p.phone,p.location].filter(Boolean).join(" | "),"",`Re: ${j.title} at ${j.company}`,"",`Dear Hiring Team,`,`I am applying for the ${j.title} role at ${j.company}. ${p.summary||"My factual profile is attached for your review."}`,`My experience and skills most relevant to this role include: ${relevant.skills.slice(0,6).join(", ")||"the experience described in my resume"}.`,`I would welcome the opportunity to discuss how my documented experience can support your team.`,`Sincerely,`,p.name];}
export async function generateMaterials(jobId:string){const d=db(),j=d.prepare("SELECT * FROM jobs WHERE job_id=?").get(jobId) as any;if(!j)throw new Error("Job not found");const p=loadProfile();if(!p)throw new Error("SETUP_REQUIRED: add private profile/profile.yaml with a factual name before generating materials.");const score=scoreJob(j.jd_original,p);const explanation=`Match: ${score.score}/100\n\nStrengths\n${score.strengths.map(x=>`✓ ${x}`).join("\n")||"No profile skills directly found."}\n\nGaps\n${score.gaps.map(x=>`△ ${x}`).join("\n")||"No identified gaps."}`;d.prepare("UPDATE jobs SET score=?,score_explanation=?,status='ANALYZED',material_status='GENERATING',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(score.score,explanation,j.id);const dir=path.join(root(),j.folder_path), revision=d.prepare("SELECT count(*) n FROM audit_events WHERE job_id=? AND action='MATERIAL_GENERATED'").get(j.id) as any, rev=revision.n+1;fs.mkdirSync(path.join(dir,"resume"),{recursive:true});fs.mkdirSync(path.join(dir,"cover_letter"),{recursive:true});fs.mkdirSync(path.join(dir,"package"),{recursive:true});const rLines=resumeLines(p,j),cLines=letterLines(p,j);const files={resumeDocx:path.join(dir,"resume","resume.docx"),resumePdf:path.join(dir,"resume","resume.pdf"),letterDocx:path.join(dir,"cover_letter","cover_letter.docx"),letterPdf:path.join(dir,"cover_letter","cover_letter.pdf"),packagePdf:path.join(dir,"package","application_package.pdf")};await writeDocx(files.resumeDocx,`${p.name} Resume`,rLines);await writeDocx(files.letterDocx,`${p.name} Cover Letter`,cLines);await writePdf(files.resumePdf,`${p.name} Resume`,rLines);await writePdf(files.letterPdf,`${p.name} Cover Letter`,cLines);const combined=await PDFDocument.create();for(const f of [files.resumePdf,files.letterPdf]){const source=await PDFDocument.load(fs.readFileSync(f));const pages=await combined.copyPages(source,source.getPageIndices());pages.forEach(page=>combined.addPage(page));}fs.writeFileSync(files.packagePdf,await combined.save());for(const f of Object.values(files)){if(!fs.existsSync(f)||fs.statSync(f).size<100)throw new Error(`Document QA failed: ${f}`);}d.prepare("UPDATE jobs SET material_status='READY',status='MATERIAL_GENERATED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(j.id);d.prepare("INSERT INTO audit_events(job_id,action,detail) VALUES(?,?,?)").run(j.id,"MATERIAL_GENERATED",JSON.stringify({revision:rev,files}));return files;}
