import fs from "node:fs";
import path from "node:path";
import { AlignmentType, BorderStyle, Document, Packer, Paragraph, TextRun } from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { db } from "./db";
import { readJobAnalysis, type TailoringPlan } from "./agent-workflow";
import { loadFactualProfile, type FactualProfile } from "./profile";
import { renderResume, type RenderCVRunner } from "./integrations/rendercv";

type Profile = FactualProfile;
const root = () => process.env.JOB_AGENT_STORAGE_ROOT || process.cwd();
const artifactPaths={resumeYaml:["resume","rendercv.yaml"],resumePdf:["resume","resume.pdf"],letterPdf:["cover_letter","cover_letter.pdf"],letterDocx:["cover_letter","cover_letter.docx"],packagePdf:["package","application_package.pdf"]} as const;
const artifactLabels={resumeYaml:"Resume RenderCV YAML",resumePdf:"Resume PDF",letterPdf:"Cover letter PDF",letterDocx:"Cover letter DOCX",packagePdf:"Application package PDF"} as const;
export type MaterialArtifact=keyof typeof artifactPaths;
export function materialArtifacts(job:any){return (Object.keys(artifactPaths) as MaterialArtifact[]).flatMap(key=>{const file=path.join(root(),job.folder_path,...artifactPaths[key]);return fs.existsSync(file)&&fs.statSync(file).isFile()?[{key,label:artifactLabels[key],file}]:[];});}
export const loadProfile = loadFactualProfile;
const paras=(lines:string[])=>lines.map((line,index)=>line.endsWith(":")?new Paragraph({border:{bottom:{color:"173F5F",style:BorderStyle.SINGLE,size:6}},spacing:{before:index?120:80,after:35},children:[new TextRun({text:line,size:19,bold:true,color:"173F5F",font:"Arial"})]}):new Paragraph({spacing:{after:32},indent:line.startsWith("•")?{left:200,hanging:120}:undefined,children:[new TextRun({text:line,size:index===0?38:18,bold:index===0,font:"Arial"})]}));
async function writeDocx(file:string,_title:string,lines:string[]) { const doc=new Document({sections:[{properties:{page:{margin:{top:600,right:650,bottom:600,left:650}}},children:paras(lines)}]}); fs.writeFileSync(file,await Packer.toBuffer(doc)); }
async function writePdf(file:string,_title:string,lines:string[]) { const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),blue=rgb(0.09,0.24,0.37); const page=pdf.addPage([595,842]);let y=800;for(const [index,text] of lines.entries()){const heading=text.endsWith(":"),f=index===0||heading?bold:font,size=index===0?22:heading?10:9;if(y<45)throw new Error("CV content exceeds the one-page budget");if(heading){page.drawText(text,{x:48,y,size,font:f,color:blue});page.drawLine({start:{x:48,y:y-4},end:{x:547,y:y-4},thickness:.6,color:blue});y-=17;continue;}const words=text.split(/\s+/);let row="";for(const word of words){const next=row?`${row} ${word}`:word;if(f.widthOfTextAtSize(next,size)>499){page.drawText(row,{x:48,y,size,font:f,color:rgb(0,0,0)});y-=size+4;row=word}else row=next;}if(row){page.drawText(row,{x:48,y,size,font:f,color:rgb(0,0,0)});y-=size+5;}} fs.writeFileSync(file,await pdf.save()); }
function tailoredProfile(p:Profile,plan:TailoringPlan){return{skills:plan.skillIndexes.map(index=>(p.skills||[])[index]),experience:plan.experiences.map(({index,bulletIndexes})=>({...p.experience![index],bullets:bulletIndexes.map(bulletIndex=>p.experience![index].bullets![bulletIndex])}))};}
function letterLines(p:Profile,j:any,plan:TailoringPlan){const relevant=tailoredProfile(p,plan);return [p.name,[p.email,p.phone,p.location].filter(Boolean).join(" | "),"",`Re: ${j.title} at ${j.company}`,"",`Dear Hiring Team,`,`I am applying for the ${j.title} role at ${j.company}. ${p.summary||"My factual profile is attached for your review."}`,`My experience and skills most relevant to this role include: ${relevant.skills.slice(0,6).join(", ")||"the experience described in my resume"}.`,`I would welcome the opportunity to discuss how my documented experience can support your team.`,`Sincerely,`,p.name];}
export async function generateMaterials(jobId:string, runner?:RenderCVRunner){const d=db(),j=d.prepare("SELECT * FROM jobs WHERE job_id=?").get(jobId) as any;if(!j)throw new Error("Job not found");if(j.content_status==="INSUFFICIENT")throw new Error("INSUFFICIENT_SOURCE_CONTENT: this job is retained for Review, but its source did not provide enough factual job-description content for tailoring or materials.");if(j.review_status!=="INTERESTED")throw new Error("INTERESTED_REQUIRED: mark this job Interested before generating materials.");const p=loadProfile();if(!p)throw new Error("SETUP_REQUIRED: add private profile/profile.yaml with a factual name before generating materials.");const analysis=readJobAnalysis(jobId);if(!analysis)throw new Error("EVALUATION_REQUIRED: persist a validated job-agent analysis before generating materials.");d.prepare("UPDATE jobs SET material_status='GENERATING',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(j.id);try{const dir=path.join(root(),j.folder_path), revision=d.prepare("SELECT count(*) n FROM audit_events WHERE job_id=? AND action='MATERIAL_GENERATED'").get(j.id) as any, rev=revision.n+1;fs.mkdirSync(path.join(dir,"cover_letter"),{recursive:true});fs.mkdirSync(path.join(dir,"package"),{recursive:true});const resume=await renderResume(p,analysis,path.join(dir,"resume"),runner);const cLines=letterLines(p,j,analysis.tailoringPlan);const files={...resume,letterDocx:path.join(dir,"cover_letter","cover_letter.docx"),letterPdf:path.join(dir,"cover_letter","cover_letter.pdf"),packagePdf:path.join(dir,"package","application_package.pdf")};await writeDocx(files.letterDocx,`${p.name} Cover Letter`,cLines);await writePdf(files.letterPdf,`${p.name} Cover Letter`,cLines);const combined=await PDFDocument.create();for(const f of [files.resumePdf,files.letterPdf]){const source=await PDFDocument.load(fs.readFileSync(f));const pages=await combined.copyPages(source,source.getPageIndices());pages.forEach(page=>combined.addPage(page));}fs.writeFileSync(files.packagePdf,await combined.save());for(const f of Object.values(files)){if(!fs.existsSync(f)||fs.statSync(f).size<100)throw new Error(`Document QA failed: ${f}`);}d.prepare("UPDATE jobs SET material_status='READY',status='MATERIAL_GENERATED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(j.id);d.prepare("INSERT INTO audit_events(job_id,action,detail) VALUES(?,?,?)").run(j.id,"MATERIAL_GENERATED",JSON.stringify({revision:rev,files}));return files;}catch(error){d.prepare("UPDATE jobs SET material_status='ERROR',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(j.id);d.prepare("INSERT INTO audit_events(job_id,action,detail) VALUES(?,?,?)").run(j.id,"MATERIAL_GENERATION_ERROR",error instanceof Error?error.message:String(error));throw error;}}
